title = "GlPortal the free action adventure"
baseurl = "http://glportal.de/"
MetaDataFormat = "yaml"
pluralizeListTitles = false


[params]
  description = "Documentation of Hugo, a fast and flexible static site generator built with love by spf13 and friends in Go"
  author = "GlPortal Team"
  gameversion = "0.1"
[taxonomies]
  tag = "tags"
  group = "groups"
[[menu.main]]
    name = "Run"
    identifier = "run"
    url = "/run"
    pre = "<i class='fa fa-rocket'></i>"
    weight = 2
[[menu.main]]
    name = "Media"
    identifier = "media"
    url = "/media"
    pre = "<i class='fa fa-image'></i>"
    weight = 9
[[menu.main]]
    name = "Download"
    pre = "<i class='fa fa-download'></i>"
    url = "/download"
    weight = 1
[[menu.main]]
    name = "About"
    pre = "<i class='fa fa-book'></i>"
    identifier = "about"
    url = "/about"
    weight = 3
[[menu.main]]
    name = "Issues & Help"
    pre = "<i class='fa fa-life-ring'></i>"
    url = "/help"
    weight = 4

[[menu.main]]
    name = "FAQ"
    identifier = "faq"
    pre = "<i class='fa fa-question-circle'></i>"
    url = "/faq"
    weight = 5

[[menu.main]]
    name = "Contribute"
    identifier = "contribute"
    pre = "<i class='fa fa-wrench'></i>"
    weight = 6
