title = "gohugo.io"
baseurl = "http://gohugo.io/"
MetaDataFormat = "yaml"
pluralizeListTitles = false

[params]
  description = "Documentation of Hugo, a fast and flexible static site generator built with love by spf13 and friends in Go"
  author = "Steve Francia (spf13) and friends"

[taxonomies]
  tag = "tags"
  group = "groups"

[[menu.main]]
    name = "Download"
    pre = "<i class='fa fa-download'></i>"
    url = "https://github.com/spf13/hugo/releases"
    weight = 1
[[menu.main]]
    name = "Quick Start Test"
    identifier = "troubleshooting"
    pre = "<i class='fa fa-wrench'></i>"
    weight = 2
[[menu.main]]
    name = "Contribute"
    identifier = "troubleshooting"
    pre = "<i class='fa fa-wrench'></i>"
    weight = 3
