baseurl = "http://gohugo.io"
MetaDataFormat = "yaml"

[indexes]
  tag = "tags"
  group = "groups"

[[menu.main]]
    name = "Download Hugo"
    pre = "<i class='fa fa-download'></i>"
    url = "https://github.com/spf13/hugo/releases"
    weight = -200
[[menu.main]]
    name = "Showcase"
    pre = "<i class='fa fa-cubes'></i>"
    url = "/showcase/"
    weight = -180